title: PLSE Conference Deadlines # (Maintained by @zhangysh1995)

description: Countdowns to top PL and SE conference deadlines
author: Yushan Zhang (forked from @abhshkdz)
domain: ""
baseurl: "https://plseddl.github.io/plse-deadlines"

twitter_username: 163Zhangysh1995
twitter_hashtag: softwareresearch
github_username: plseddl
github_repo: plse-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
