title: PLSE Conference Deadlines # (Maintained by @zhangysh1995)

description: Countdowns to top PL and SE conference deadlines
author: Yushan Zhang (forked from @abhshkdz)
domain: ""
baseurl: "https://github.com/brEisMEr/ai-deadlines/blob/pl%2Bse/_config.yml"

twitter_username: 163Zhangysh1995
twitter_hashtag: 
github_username: zhangysh1995
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
