title: "PL SE Conference Deadlines"
description: "Stay updated with countdowns to top programming languages and software engineering conference deadlines."
author: Madhurima Chakraborty (forked from @zhangysh1995 who forked from @abhshkdz :P)
baseurl: "/plse-deadlines"
twitter_username: "FriendingNimmo"
github_username: "madhunimmo"
github_repo: "plse-deadlines"
markdown: "kramdown"
ga_id: "UA-36274081-2"
include: ['_pages']

