name: Auto Delete Past Conferences

on:
  workflow_dispatch:
  # schedule:
  #  - cron: '0 0 * * *'  # This line sets the action to run automatically daily at midnight

jobs:
  delete-past-conferences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2  # This action checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensures you use the latest version of Python 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml pyyaml  # Installs both ruamel.yaml and PyYAML

      - name: Run script to delete past conferences
        run: python .github/workflows/auto_delete_conf.py
